# Generated by Django 3.2.20 on 2023-09-01 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_message_is_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_sent',
        ),
    ]
