# Generated by Django 3.2.20 on 2023-09-03 15:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_message_is_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='cloudinary_image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/krystalcoding/image/upload/v1693749946/pexels-james-wheeler-1598075_snnext.jpg', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
