# Generated by Django 3.2.20 on 2023-09-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_photo_cloudinary_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cloudinary_featured_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='local_featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
